// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class AcaMembers
    {
        public int MemIdx { get; set; }
        public string UserId { get; set; }
        public string UserPw { get; set; }
        public string Name { get; set; }
        public byte Level { get; set; }
        public bool UseYn { get; set; }
        public DateTime? Regdate { get; set; }
    }
}