// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class AcaQuestions
    {
        public int QIdx { get; set; }
        public DateTime BaseDate { get; set; } = DateTime.Now.Date;
        public int TIdx { get; set; } = 0;
        public int StuIdx { get; set; } = 0;
        public string TName { get; set; } = string.Empty;
        public string StuName { get; set; } = string.Empty;
        public string QSubject { get; set; } = string.Empty;
        public string Etc1 { get; set; } = string.Empty;
        public DateTime RegDate { get; set; } = DateTime.Now;
    }
}