// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DocumentFormat.OpenXml.Wordprocessing;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using tjdaca.Class;

namespace tjdaca.Data
{
    public partial class AcaRawdata
    {
        [Display(Name = "Index")]
        public int RIdx { get; set; }

        [Display(Name = "일자")]
        public DateTime BaseDate { get; set; } = DateTime.Now.Date;

        [Display(Name = "반명")]
        public string ClassName { get; set; } = string.Empty;

        [IgnoreExcelAttribute]
        public int? TIdx { get; set; } = 0;

        [Display(Name = "학생번호")]
        public int? StuIdx { get; set; } = 0;

        [Display(Name = "학생이름")]
        public string StuName { get; set; } = string.Empty;

        [Display(Name = "학교구분")]
        public string SchType { get; set; } = string.Empty;

        [Display(Name = "학교명")]
        public string SchName { get; set; } = string.Empty;

        [Display(Name = "학년")]
        public string Grade { get; set; } = string.Empty;

        [Display(Name = "출석여부")]
        public string Attendance { get; set; } = "O";

        [Display(Name = "결석사유")]
        public string AbsenceReason { get; set; } = string.Empty;

        [Display(Name = "학교시험성적")]
        public string SchAchievement { get; set; } = string.Empty;

        [Display(Name = "수업내용")]
        public string ClassSubject { get; set; } = string.Empty;

        [Display(Name = "수업학년-학기")]
        public string ClassGrade { get; set; } = string.Empty;
        
        [Display(Name = "과제내용과 양")]
        public string Homework { get; set; } = string.Empty;

        [Display(Name = "과제이행여부")]
        public bool HomeworkYn { get; set; } = false;

        [Display(Name = "이전과제량")]
        public float? HomeworkPrev { get; set; } = null;

        [Display(Name = "과제수행량")]
        public float? HomeworkPerform { get; set; } = null;

        [Display(Name = "과제정답")]
        public float? HomeworkCorrect { get; set; } = null;

        [Display(Name = "과제이행정도")]
        public float? HomeworkProgress { get; set; } = null;

        [Display(Name = "과제정답률")]
        public float? HomeworkRatio { get; set; } = null;

        [Display(Name = "테스트학기")]
        public string TestGrade { get; set; } = string.Empty;

        [Display(Name = "테스트단원")]
        public string TestSubject { get; set; } = string.Empty;

        [Display(Name = "교재출처")]
        public string TextbookSource { get; set; } = string.Empty;

        [Display(Name = "난이도")]
        public string Difficulty { get; set; } = string.Empty;

        [Display(Name = "일일테스트여부")]
        public bool DailyYn { get; set; } = false;

        [Display(Name = "일일테스트문항수")]
        public float? DaliyCount { get; set; } = null;

        [Display(Name = "일일테스트정답수")]
        public float? DailyCorrect { get; set; } = null;

        [Display(Name = "일일테스트정답률")]
        public float? DailyScore { get; set; } = null;

        [Display(Name = "클리닉진행여부")]
        public bool CliniqYn { get; set; } = false;

        [Display(Name = "클리닉담임")]
        public string CliniqTeacher { get; set; } = string.Empty;

        [Display(Name = "클리닉학기")]
        public string CliniqGrade { get; set; } = string.Empty;

        [Display(Name = "클리닉 단원")]
        public string CliniqSubject { get; set; } = string.Empty;

        [Display(Name = "클리닉테스트문항수")]
        public float? CliniqCount { get; set; } = null;

        [Display(Name = "클리닉테스트정답수")]
        public float? CliniqCorrect { get; set; } = null;

        [Display(Name = "클리닉테스트정답률")]
        public float? CliniqScore { get; set; } = null;

        [Display(Name = "월간상담내용")]
        public string Counsel { get; set; } = string.Empty;

        [Display(Name = "특이사항")]
        public string Etc1 { get; set; } = string.Empty;

        [IgnoreExcelAttribute]
        public string Etc2 { get; set; } = string.Empty;
        [IgnoreExcelAttribute]
        public string Etc3 { get; set; } = string.Empty;

        [Display(Name = "등록일")]
        public DateTime? RegDate { get; set; } = DateTime.Now;
    }
}