// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class AcaStuExamScore
    {
        public int Idx { get; set; }
        public int StuIdx { get; set; }
        public string StuName { get; set; }
        public int? Year { get; set; }
        public int? Month { get; set; }
        public float? Score { get; set; }
        public string ReportUrl { get; set; }
        public DateTime RegDate { get; set; }
    }
}