// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class AcaStudents
    {
        public int StuIdx { get; set; }
        public string StuName { get; set; }
        public string StudentPhone { get; set; }
        public string Parent { get; set; }
        public string ParentPhone { get; set; }
        public string Zipcode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string School { get; set; }
        /// <summary>
        /// 초등/중등/고등
        /// </summary>
        public string SchType { get; set; }
        /// <summary>
        /// 학년
        /// </summary>
        public string SchGrade { get; set; }
        public string HopeHighschool { get; set; }
        public string HopeUniversity { get; set; }
        public string Subject { get; set; }
        public string SubjectOption { get; set; }
        public string MathProgress { get; set; }
        public string CognitivePathway { get; set; }
        public string VisitPurpose { get; set; }
        public bool Agree { get; set; }
        public DateTime? AcaRegdate { get; set; }
        public DateTime? AcaOutdate { get; set; }
        public string Teacher { get; set; }
        public DateTime? TestDate { get; set; }
        public string TestArea { get; set; }
        public string TestScore { get; set; }
        public string TestResult { get; set; }
        public string Class { get; set; }
        public string Etc1 { get; set; }
        public string Etc2 { get; set; }
        public string Etc3 { get; set; }
        public string Etc4 { get; set; }
        public string Etc5 { get; set; }
        public string Etc6 { get; set; }
        public string Etc7 { get; set; }
        public string Etc8 { get; set; }
        public string Etc9 { get; set; }
        public DateTime Regdate { get; set; }
        public DateTime Lastdate { get; set; }
    }
}