// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class AcaSubject
    {
        public int MIdx { get; set; }
        public string Subject { get; set; }
        public string Grade { get; set; }
        public string Value { get; set; }
    }
}