// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class AcaStuSchoolScore
    {
        public int Idx { get; set; }
        public int StuIdx { get; set; }
        public string StuName { get; set; }
        public float? M11 { get; set; }
        public float? M12 { get; set; }
        public float? M21 { get; set; }
        public float? M22 { get; set; }
        public float? M31 { get; set; }
        public float? M32 { get; set; }
        public float? H11 { get; set; }
        public float? H12 { get; set; }
        public float? H21 { get; set; }
        public float? H22 { get; set; }
        public float? H31 { get; set; }
        public float? H32 { get; set; }
        public DateTime RegDate { get; set; }

        public AcaStuSchoolScore() { }
        public AcaStuSchoolScore(int id)
        {
            this.StuIdx = id;
            this.M11 = 0;
            this.M12 = 0;
            this.M21 = 0;
            this.M22 = 0;
            this.M31 = 0;
            this.M32 = 0;
            this.H11 = 0;
            this.H12 = 0;
            this.H21 = 0;
            this.H22 = 0;
            this.H31 = 0;
            this.H32 = 0;
            this.RegDate = DateTime.Now;
        }
    }
}