// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class Options
    {
        public int OIdx { get; set; }
        public string OptType { get; set; }
        public string OptValue { get; set; }
        public int OptOrder { get; set; }
    }
}