// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class Questions
    {
        public int QIdx { get; set; }
        public DateOnly BaseDate { get; set; }
        public int? TIdx { get; set; }
        public int? StuIdx { get; set; }
        public string QSubject { get; set; }
        public string Etc1 { get; set; }
        public DateTime? RegDate { get; set; }
    }
}