// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class Rawdata
    {
        public int RIdx { get; set; }
        public DateTime? BaseDate { get; set; }
        public string ClassName { get; set; }
        public int? TIdx { get; set; }
        public int? StuIdx { get; set; }
        public string SchType { get; set; }
        public string SchName { get; set; }
        public string Grade { get; set; }
        public string Attendance { get; set; }
        public string AbsenceReason { get; set; }
        public string SchAchievement { get; set; }
        public string ClassSubject { get; set; }
        public string ClassGrade { get; set; }
        public string Homework { get; set; }
        public float? HomeworkPrev { get; set; }
        public float? HomeworkPerform { get; set; }
        public float? HomeworkCorrect { get; set; }
        public float? HomeworkProgress { get; set; }
        public float? HomeworkRatio { get; set; }
        public string TestSubject { get; set; }
        public string TextbookSource { get; set; }
        public string Difficulty { get; set; }
        public float? DaliyCount { get; set; }
        public float? DailyCorrect { get; set; }
        public float? DailyScore { get; set; }
        public string CliniqSubject { get; set; }
        public float? CliniqCount { get; set; }
        public float? CliniqCorrect { get; set; }
        public float? CliniqScore { get; set; }
        public string Counsel { get; set; }
        public string Etc1 { get; set; }
        public string Etc2 { get; set; }
        public string Etc3 { get; set; }
        public DateTime? RegDate { get; set; }
    }
}