// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class Schools
    {
        public int SchIdx { get; set; }
        public string SchName { get; set; }
        public DateTime? Regdate { get; set; }
    }
}