// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class Students
    {
        public int StuIdx { get; set; }
        public string StuName { get; set; } = string.Empty;
        public string StudentPhone { get; set; } = string.Empty;
        public string Parent { get; set; } = string.Empty;
        public string ParentPhone { get; set; } = string.Empty;
        public string Zipcode { get; set; } = string.Empty;
        public string Address1 { get; set; } = string.Empty;
        public string Address2 { get; set; } = string.Empty;    
        public string School { get; set; } = string.Empty;
        public string SchType { get; set; } = string.Empty;
        public string SchGrade { get; set; } = string.Empty;
        public string HopeHighschool { get; set; } = string.Empty;  
        public string HopeUniversity { get; set; } = string.Empty;
        public string Subject { get; set; } = string.Empty;
        public string SubjectOption { get; set; } = string.Empty;
        public string MathProgress { get; set; } = string.Empty;
        public string CognitivePathway { get; set; } = string.Empty;
        public string VisitPurpose { get; set; } = string.Empty;
        public bool Agree { get; set; }   
        public DateTime AcaRegdate { get; set; }
        public DateTime AcaOutdate { get; set; }
        public string Teacher { get; set; } = string.Empty;
        public DateTime TestDate { get; set; }
        public string TestResult { get; set; } = string.Empty;
        public string Class { get; set; } = string.Empty;
        public string Etc1 { get; set; }= string.Empty;
        public string Etc2 { get; set; }= string.Empty;
        public string Etc3 { get; set; }= string.Empty;
        public string Etc4 { get; set; }= string.Empty;
        public string Etc5 { get; set; }= string.Empty;
        public string Etc6 { get; set; }= string.Empty;
        public string Etc7 { get; set; }= string.Empty;
        public string Etc8 { get; set; }= string.Empty;
        public string Etc9 { get; set; } = string.Empty;
        public DateTime Regdate { get; set; } = DateTime.Now;
        public DateTime Lastdate { get; set; } = DateTime.Now;
    }
}