// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tjdaca.Data
{
    public partial class Teachers
    {
        public int TIdx { get; set; }
        public string TName { get; set; }
        public DateTime? Regdate { get; set; }
    }
}